### ISSUE TITLE
Incompatible with Fresh Animations 1.9

### ISSUE THREAD

**Issue by jg2002-j** [VixelCreates/VanillaEvolved#5]
Hi, amazing resourcepack ♥. When I try to load both this pack (VanillaEvolved_1.7.0 for 1.20.1) and Fresh Animations (v1.9) the resources fail with the error: 
![image](https://github.com/VixelCreates/VanillaEvolved/assets/85451562/ca8b3460-7620-4ad9-ba15-3e703bff917a)

Lmk if you need more info :)

**Comment by VixelCreates** [comment]
Hi there!
Thanks for the report.
I just tested the same version and there seems to be no problems.
Maybe there is an incompatibility with another pack/mod.
Also make sure to put fresh animations on top of your resource pack list to avoid texture issues.

**Comment by SecretyKyro** [comment]
In my case, the texture pack does not load at all, even only by itself. Is there any known mod incompatibility? I'm in version 1.20.6, using Fabric.

**Comment by VixelCreates** [comment]
Hi! I've tested the Resource Pack with a freshly installed version of Minecraft and have noticed no problems.

There are no known mod incompatibilities with the Resource Pack.
At least there have been no reports, and technically there shouldn't be any problems with mods, since it's a resource pack that only applies modifications to vanilla content.

also make sure you downloaded the Resource Pack from the trusted sources (modrinth/PlanetMinecraft).
If you can provide more details, I'll be happy to help.

**Comment by Fyoncle** [comment]
Merchant Markers usually cause this, or Bushy Leaves [Mod Support] when you try it on forge.

**Comment by VixelCreates** [comment]
Sorry for the delay in responding
if you are still experiencing issues, please update to the latest resourcepack version and report back
Also let me know if you can provide any information from the logs on what the exact error is that occurs when using the resource pack.
The reason for this problem is still unclear

**Comment by VixelCreates** [comment]
In my recent tests with the Fresh Animation Resource Pack, I haven't experienced any problems.
I'm closing this page for now.
